appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: UNC1/ziheR8qxRB8kQphbguO/VOySoInKNOlmKqyEOazpUohj4Xg1ARAJqZHjnkR4FuxmTZqJ6GB4R1AHkCMJE7OBGugPbFT5GEX9qAurRiX3hnUuyiC3Eug7PIRUpo8JoQv/q7g6GPP0ztaXGuGMxWa/iyeyBtFifMGRzyD7oBdkue5jXmvX5F8jz02J25Zblgsl9E+u40MIS3DPW8t8rkRpiqHwo/WLom4iVFHlxpu841oEWHLuzLKO4USXvCipAJD3BT39JTYM2qzJSODES1Fs/HVhjMNPzfx1ZxvZp8anCCov142rcb2ZVpaxGVm9MnoTA4herr3mAnCSYw9r13IeE52bmHX7zQ63FYkczzQapj+Au1fstaXUXRf0eq3S/PB1JaeXoPgQU8ACL2VfPirgZLRgOryVyV5Bh1qBUMcAVQCRK/TngNNLLOhtpeEplkn8GD/6tkjgoJlD27mtdapRsObZnVOpTIE0z+vOhTW7tHBxQfqf1IAUk12zV+04aJbLoNB8ROobAudlCdBJ0BjmFEajmjPL8K64qkShhWCP/ogQxcOb/WRkpvRIq2EWxQRALEHPPsCXzEHNwqbkSpR9b929cTZBiJvEoiiHgyMbAcZu8I04B0CYhxFJZaeKz+iPAbiwqQc3Dqfou1AlWWmxRnVLeLkHp4pw/eRVzk=}
provider:
  win: azure
conda_forge_output_validation: false
